#!/bin/bash

mount -t proc       proc        /proc   -o nosuid,noexec,nodev
mount -t sysfs      sys         /sys    -o nosuid,noexec,nodev
mount -t devtmpfs   dev         /dev    -o mode=0755,nosuid
mount -t tmpfs      run         /run    -o nosuid,nodev,mode=0755
mount -t tmpfs      tmpfs       /tmp
mkdir -m755 /run/initramfs

kmod static-nodes --format=tmpfiles --output=/run/tmpfiles.d/kmod.conf
systemd-tmpfiles --prefix=/dev --create --boot
/usr/lib/systemd/systemd-udevd --daemon --resolve-names=never
udevadm trigger --action=add --type=subsystems
udevadm trigger --action=add --type=devices
udevadm settle

/usr/bin/setsid bash -c "exec /bin/bash -i <dev/console >/dev/console 2>&1"

